/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package conversores.controlador;

import conversores.objetos.*;
import javax.swing.JOptionPane;

/**
 *
 * @author fran
 */
public class VController extends javax.swing.JFrame {

    /**
     * Creates new form VController
     */
    
    Finanzas finanzas;
    Temperatura temperatura;
    Numero numero;
    
    public VController() {
        finanzas = new Finanzas();
        temperatura = new Temperatura();
        numero = new Numero();
        initComponents();
        setLocationRelativeTo(null);
        dolars.setText("");
        euros.setText("");
        frases.setText("");
        celsius.setText("");
        fahrenheit.setText("");
        doble.setText("");
        triple.setText("");
        resultado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        moneda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dolars = new javax.swing.JLabel();
        euros = new javax.swing.JLabel();
        frases = new javax.swing.JLabel();
        buttonEuros = new javax.swing.JButton();
        buttonDolars = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        vTemperatura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        celsius = new javax.swing.JLabel();
        fahrenheit = new javax.swing.JLabel();
        buttonFahrenheit = new javax.swing.JButton();
        buttonCelsius = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sumaResta = new javax.swing.JTextField();
        buttonSuma = new javax.swing.JButton();
        buttonResta = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        buttonDoble = new javax.swing.JButton();
        buttonTriple = new javax.swing.JButton();
        doble = new javax.swing.JLabel();
        triple = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio de Conversores");

        jLabel1.setText("Introduce el valor a convertir");

        jLabel2.setText("Valor en dolares");

        jLabel3.setText("Valor en euros");

        dolars.setText("jLabel4");

        euros.setText("jLabel5");

        frases.setText("jLabel6");

        buttonEuros.setText("Convertir a euros");
        buttonEuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEurosActionPerformed(evt);
            }
        });

        buttonDolars.setText("Convertir a dolares");
        buttonDolars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDolarsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moneda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(euros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dolars, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 328, Short.MAX_VALUE))
                    .addComponent(frases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonDolars)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEuros)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dolars))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(euros))
                .addGap(40, 40, 40)
                .addComponent(frases)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEuros)
                    .addComponent(buttonDolars))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Conversor de moneda", jPanel1);

        jLabel4.setText("Introduce el valor a convertir");

        jLabel5.setText("Valor en grados Celsius");

        jLabel6.setText("Valor en grados Fahrenheit");

        celsius.setText("jLabel7");

        fahrenheit.setText("jLabel8");

        buttonFahrenheit.setText("Convertir a Fahrenheit");
        buttonFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFahrenheitActionPerformed(evt);
            }
        });

        buttonCelsius.setText("Convertir a Celsius");
        buttonCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCelsiusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(vTemperatura))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(celsius, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fahrenheit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 330, Short.MAX_VALUE)
                        .addComponent(buttonCelsius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFahrenheit)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(celsius))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFahrenheit)
                    .addComponent(buttonCelsius))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Conversor de temperatura", jPanel2);

        jLabel7.setText("Introduce un numero entero");

        jLabel8.setText("Introduce un valor para sumar o restar");

        buttonSuma.setText("Sumar");
        buttonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSumaActionPerformed(evt);
            }
        });

        buttonResta.setText("Restar");
        buttonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestaActionPerformed(evt);
            }
        });

        jLabel9.setText("Resultado");

        resultado.setText("jLabel10");

        buttonDoble.setText("Duplicar");
        buttonDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDobleActionPerformed(evt);
            }
        });

        buttonTriple.setText("Triplicar");
        buttonTriple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTripleActionPerformed(evt);
            }
        });

        doble.setText("jLabel11");

        triple.setText("jLabel12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sumaResta, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonSuma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonResta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(buttonTriple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(triple))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(buttonDoble)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doble)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sumaResta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSuma)
                    .addComponent(buttonResta)
                    .addComponent(jLabel9)
                    .addComponent(resultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDoble)
                    .addComponent(doble))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTriple)
                    .addComponent(triple))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conversor de numeros", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEurosActionPerformed
        // TODO add your handling code here:
        try{
            double resultado = finanzas.eurosToDolars(Double.parseDouble(moneda.getText()));
            dolars.setText(resultado + "");
            euros.setText(moneda.getText());
            if(resultado == 5.0){
                frases.setText("Five dollars beaucoup dollars");
            }
            else{
                frases.setText("");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No comprendo el valor que me pasas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonEurosActionPerformed

    private void buttonDolarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDolarsActionPerformed
        // TODO add your handling code here:
        try{
            dolars.setText(moneda.getText());
            euros.setText(finanzas.dolaresToEuros(Double.parseDouble(moneda.getText())) + "");
            if(Double.parseDouble(moneda.getText()) == 5.0){
                frases.setText("Five dollars beaucoup dollars");
            }
            else{
                frases.setText("");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No comprendo el valor que me pasas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonDolarsActionPerformed

    private void buttonFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFahrenheitActionPerformed
        // TODO add your handling code here:
        try{
            fahrenheit.setText(temperatura.celsiusToFarenheit(Double.parseDouble(vTemperatura.getText())) + "");
            celsius.setText(vTemperatura.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No comprendo el valor que me pasas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonFahrenheitActionPerformed

    private void buttonCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCelsiusActionPerformed
        // TODO add your handling code here:
        try{
            celsius.setText(temperatura.farenheitToCelsius(Double.parseDouble(vTemperatura.getText())) + "");
            fahrenheit.setText(vTemperatura.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No comprendo el valor que me pasas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonCelsiusActionPerformed

    private void buttonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSumaActionPerformed
        // TODO add your handling code here:
        try{
            numero.setNumero(Integer.parseInt(valor.getText()));
            resultado.setText("" + numero.añadir(Integer.parseInt(sumaResta.getText())));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No comprendo el valor que me pasas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonSumaActionPerformed

    private void buttonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestaActionPerformed
        // TODO add your handling code here:
        try{
            numero.setNumero(Integer.parseInt(valor.getText()));
            resultado.setText("" + numero.restar(Integer.parseInt(sumaResta.getText())));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No comprendo el valor que me pasas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonRestaActionPerformed

    private void buttonDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDobleActionPerformed
        // TODO add your handling code here:
        try{
            numero.setNumero(Integer.parseInt(valor.getText()));
            doble.setText("" + numero.getDoble());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No comprendo el valor que me pasas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonDobleActionPerformed

    private void buttonTripleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTripleActionPerformed
        // TODO add your handling code here:
        try{
            numero.setNumero(Integer.parseInt(valor.getText()));
            triple.setText("" + numero.getTriple());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No comprendo el valor que me pasas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonTripleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCelsius;
    private javax.swing.JButton buttonDoble;
    private javax.swing.JButton buttonDolars;
    private javax.swing.JButton buttonEuros;
    private javax.swing.JButton buttonFahrenheit;
    private javax.swing.JButton buttonResta;
    private javax.swing.JButton buttonSuma;
    private javax.swing.JButton buttonTriple;
    private javax.swing.JLabel celsius;
    private javax.swing.JLabel doble;
    private javax.swing.JLabel dolars;
    private javax.swing.JLabel euros;
    private javax.swing.JLabel fahrenheit;
    private javax.swing.JLabel frases;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField moneda;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField sumaResta;
    private javax.swing.JLabel triple;
    private javax.swing.JTextField vTemperatura;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
